### PR TITLE
Update message error

### PR DESCRIPTION
**Pull request by Onotoko**
Change msg error from `Invalid grant: authorization code is invalid` to `'Invalid grant: client.id in authorization code not match with client_id in body of api`

### CODE REVIEW

**Comment by Onotoko** [comment]
@flowersinthesand, pls help me review and change it

**Comment by flowersinthesand** [comment]
@Onotoko The following test failed:

``` 
1 failing

  1) AuthorizationCodeGrantType integration
       getAuthorizationCode()
         should throw an error if the client id does not match:

      AssertionError: expected 'Invalid grant: client.id in authorization code not match with client_id in body of api' to be 'Invalid grant: authorization code is invalid'
      + expected - actual

      -Invalid grant: client.id in authorization code not match with client_id in body of api
      +Invalid grant: authorization code is invalid
      
      at Assertion.fail (node_modules/should/cjs/should.js:275:17)
      at Assertion.value (node_modules/should/cjs/should.js:356:19)
      at /Users/donghwankim/git/onotoko-node-oauth2-server/test/integration/grant-types/authorization-code-grant-type_test.js:322:28
      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:512:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:569:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:689:18)
      at Async._drainQueue (node_modules/bluebird/js/release/async.js:133:16)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:143:10)
      at Immediate.Async.drainQueues (node_modules/bluebird/js/release/async.js:17:14)
```

Also, why do you want to update the message? I think the original one is fine in that it doesn't reveal the details.

**Comment by Onotoko** [comment]
@flowersinthesand, I know this error. 
> why do you want to update the message

Because It is not authorization code invalid, it involves to client id in body of request & client.id in authorization code model. So I think we should change for clearly.
If you think it's not necessary, I will close PR

**Comment by flowersinthesand** [comment]
@Onotoko It's not realistic IMO. Anyway, please either fix the https://github.com/flowersinthesand/node-oauth2-server/pull/2#issuecomment-485685154 or rollback the updated message.

**Comment by Onotoko** [comment]
Okay,  I will close this  PR

**Pull request closed without merging**
